# -*- coding: utf-8 -*-
"""ADS ft MQ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LbtZye772-uQjqem1BPaEQBhfbkmoVI
"""

import time
import board
import busio
from adafruit_ads1x15.ads1115 import ADS
from adafruit_ads1x15.analog_in import AnalogIn

i2c = busio.I2C(board.SCL, board.SDA)

# Create the ADS object and specify the gain
# Can change based on the voltage signal - Gain of 1 is typically enough for a lot of sensors
ads = ADS.ADS1115(i2c)
ads.gain = 1
chan = AnalogIn(ads, ADS.P0)

# Continuously print the values
while True:
    print(f"MQ-135 Voltage: {chan.voltage}V")
    time.sleep(1)